export enum PATHS {
	HOME = '/',
	MY_MAIN = '/my/main',
	MY_ORDER_LIST = '/my/orderlist',
	MY_FAVORITES = '/my/favorites',
	MY_SETTINGS = '/my/settings',
	CART = '/cart',
	CATEGORY = '/category/',
	PRODUCT = '/product/',
	ADMIN = '/admin',
	ADMIN_USERS = '/admin/users',
	ADMIN_CATEGORIES = '/admin/categories',
	ADMIN_CATEGORY = '/admin/category/',
	ADMIN_PRODUCTS = '/admin/products',
	ADMIN_PRODUCT = '/admin/product',
}
