import '../assets/styles/globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import { Header } from '@/components/layout/Header/Header'

const inter = Inter({ subsets: ['latin'], display: 'swap' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
																		 children,
																	 }: {
	children: React.ReactNode
}) {
	return (
		<html lang='en' className={inter.className}>
		<body>
		<div className='root'>
			<Header />
			<div className={'root-layout'}>
				{children}
			</div>
		</div>
		</body>
		</html>
	)
}
